spring.application.name=auth-service

server.port=${AUTH_SERVER_PORT:8085}

spring.data.mongodb.uri=${AUTH_MONGODB_URI:mongodb://localhost:27017/wisdom_lms_auth}

spring.data.mongodb.database=${AUTH_MONGODB_DATABASE:wisdom_lms_auth}
