spring.application.name=gateway-service

server.port=8080


# ========================
# AUTH SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URI:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.rate-limiter=#{@simpleRateLimiter}
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}


# ========================
# CLASS SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[1].id=class-service
spring.cloud.gateway.server.webflux.routes[1].uri=${CLASS_SERVICE_URI:http://localhost:8084}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/classes/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AddRequestHeader=X-API-KEY,wisdom-lms-secret-key


# ========================
# TEACHER SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[2].id=teacher-service
spring.cloud.gateway.server.webflux.routes[2].uri=${TEACHER_SERVICE_URI:http://localhost:8083}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/teachers/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=AddRequestHeader=X-API-KEY,wisdom-teacher-secret-2026


# ========================
# STUDENT SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[3].id=student-service
spring.cloud.gateway.server.webflux.routes[3].uri=${STUDENT_SERVICE_URI:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/students/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=AddRequestHeader=X-API-KEY,student-secret-2026


# ========================
# PAYMENT SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[4].id=payment-service
spring.cloud.gateway.server.webflux.routes[4].uri=${PAYMENT_SERVICE_URI:http://localhost:8085}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/payments/**, /payments/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=RewritePath=/api/payments(?<segment>/?.*), /payments$\{segment}
spring.cloud.gateway.server.webflux.routes[4].filters[1]=AddRequestHeader=X-API-KEY,wisdom-payment-key-2026


# ========================
# CORS
# ========================

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
