spring.application.name=gateway-service

server.port=8080


# ========================
# AUTH SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.rate-limiter=#{@simpleRateLimiter}
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}


# ========================
# CLASS SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[1].id=class-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/classes/**

spring.cloud.gateway.server.webflux.routes[1].filters[0]=AddRequestHeader=X-API-KEY,wisdom-lms-secret-key


# ========================
# TEACHER SERVICE
# ========================

spring.cloud.gateway.server.webflux.routes[2].id=teacher-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/teacher/**


# ========================
# CORS
# ========================

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true