spring.application.name=payment-service

server.port=${PAYMENT_SERVER_PORT:8086}

spring.data.mongodb.uri=${PAYMENT_MONGODB_URI:mongodb://localhost:27017/wisdom_payment}

payment.api.key=${PAYMENT_API_KEY:wisdom-payment-key-2026}
