spring.application.name=class-service
server.port=8084

spring.mongodb.uri=${MONGODB_URI:mongodb://wisdomadmin:wisdommongo123@localhost:27020/wisdom_class_db?authSource=admi
spring.web.error.include-message=always
spring.web.error.include-stacktrace=never

app.api-key=${API_KEY:wisdom-class-secret-2026}